---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  WYOMING_WHISPER_VERSION: 2.1.0