---
version: latest-r36.2.0-cu122-cp311
slug: faster-whisper
name: Faster Whisper
description: Speech-to-text with Faster Whisper on NVIDIA Jetson
url: https://github.com/dusty-nv/jetson-containers/tree/master/packages/smart-home/wyoming/wyoming-whisper
arch:
  - aarch64
init: false
machine:
  - '!intel-nuc'
  - '!odroid-c2'
  - '!odroid-n2'
  - '!odroid-xu'
  - 'qemuarm-64'
  - '!qemuarm'
  - '!qemux86-64'
  - '!qemux86'
  - '!raspberrypi'
  - '!raspberrypi2'
  - '!raspberrypi3-64'
  - '!raspberrypi3'
  - '!raspberrypi4-64'
  - '!raspberrypi4'
  - '!raspberrypi5-64'
  - '!tinker'
discovery:
  - wyoming
backup_exclude:
  - "*.bin"
  - "*.onnx"
options:
  model: tiny-int8
  language: en
  beam_size: 1
  debug_logging: false
  use_cuda: true
schema:
  model: |
    list(tiny-int8|tiny|tiny.en|base-int8|base|base.en|small-int8|distil-small.en|small|small.en|distil-medium.en|medium-int8|medium|medium.en|large|large-v1|distil-large-v2|large-v2|large-v3|custom)
  custom_model: str?
  language: |
    list(auto|af|am|ar|as|az|ba|be|bg|bn|bo|br|bs|ca|cs|cy|da|de|el|en|es|et|eu|fa|fi|fo|fr|gl|gu|ha|haw|he|hi|hr|ht|hu|hy|id|is|it|ja|jw|ka|kk|km|kn|ko|la|lb|ln|lo|lt|lv|mg|mi|mk|ml|mn|mr|ms|mt|my|ne|nl|nn|no|oc|pa|pl|ps|pt|ro|ru|sa|sd|si|sk|sl|sn|so|sq|sr|su|sv|sw|ta|te|tg|th|tk|tl|tr|tt|uk|ur|uz|vi|yi|yo|zh|yue)
  beam_size: int
  initial_prompt: str?
  debug_logging: bool
  use_cuda: bool
ports:
  "10300/tcp": null
homeassistant: 2023.8.0.dev20230728
image: ms1design/wyoming-whisper